@startuml
start
:Начало приемки смены;
:Проверить внешнее состояние станка;
if (Повреждения есть?) then (Да)
  :Уведомить мастера/наладчика;
  :Запись в журнал оператора;
endif

:Проверить качество уборки;
if (Жидкости/стружка найдены?) then (Да)
  :Уведомить мастера/наладчика;
  :Запись в журнал оператора;
endif

:Проверить готовность станка к работе;
if (Искрение/шумы?) then (Да)
  :Уведомить мастера/наладчика;
  :Запись в журнал оператора;
endif

:Проверить режущий инструмент;
if (Нехватка/поломка?) then (Да)
  :Уведомить мастера/наладчика;
  :Запись в журнал оператора;
endif

:Проверить измерительный инструмент;
if (Повреждения есть?) then (Да)
  :Уведомить мастера/наладчика;
  :Запись в журнал оператора;
endif

:Проверить комплектацию тумбы;
if (Нехватка есть?) then (Да)
  :Уведомить мастера/наладчика;
  :Запись в журнал оператора;
endif

:Запись в журнал оператора;
if (Замечания есть?) then (Да)
  :Уведомить начальника производства;
endif

:Подтверждение приемки смены;
stop
@enduml
