@startmindmap
* Мастер
** Производственные вопросы
*** Обеспечение заготовками
*** Обеспечение инвентарем и инструментами
**** Контроль наличия и целостности
*** Транспортировка остатков заготовок
**** Приемка на склад
*** Транспортировка деталей
**** Контролерам, на последующие операции
**** На участки слесарки и упаковки
*** Контроль отгрузки
*** Закрытие отчетов
**** На основании решений контролеров
** Непроизводственные вопросы
*** Контроль смен
**** Приемка и передача смен
*** Техническое обслуживание станков
*** Чистота и порядок
**** Уборка стружки, масла и т.д.
*** Обеспечение пластиковыми стяжками
*** Контроль оборудования
**** Исправность общего оборудования
*** Комплектация тумб
** Организационные вопросы
*** График смен
*** Дополнительные смены
**** Согласование выхода
*** Коммуникация с сотрудниками
**** Начальник производства
**** Учебный центр
**** Кадровый инспектор
** Взаимодействие со стажерами
*** Знакомство через начальника учебного центра
*** Выделение шкафчиков
*** Экскурсия по цеху
**** Первый рабочий день
*** Помощь в адаптации
**** Ответы на вопросы
**** Коммуникация с сотрудниками
@endmindmap
